= 2015/5/24 牛津先生門下発表会に賛助出演
:published_at: 2015-05-24
:hp-alt-title: ushidu2015

昨日は、「キラリ富士見」マルチホールというところでムジナリータ&タピーロでお世話になっている牛津佐和子先生のピアノ教室の発表会がありました。

去年はその日に行って強引に楽譜を渡し、歌わせてもらった(三好さん本当にありがとうございます)のですが、今回はさすがに事前に渡しました笑

複数回レッスンを受けていた曲をやらせてもらったのも功を奏し、割と成長が実感できるステージだったのでは、と思います。

== 発表会全体の感想
コンテンツとしては、大きく分けて

* 子供の歌
* 子供のピアノ
* 大人の歌

という3つでした。一番学ぶものが多かったのは、子供の歌ですかね。

「表現」とはいったい何だったか、というのを思い出させてくれる演奏ばかりで、見習うべきところが非常に多かったです。

大人の歌（ムジナのメンバーによる独唱）も、やはりステージというのはその人のステータスが明らかになるものだなあ、とこわさとともに面白さを感じていました。


== 自分の成果
やった曲は、_"quella fiamma che m'accende(私を燃え立たせるあの炎)"_という、コンティ作曲のレチタティーヴォ+アリアです。マルチェッロ作曲とも言われていますが…

曲自体はバロックのものですが、パリゾッティ・フィルタを通しているため、非常にロマンティックな造りになっています。そこで、今回は*二つの文化のハイブリッドな感じをリハーサル・会話・本番を通じてピアニストに伝えて一緒に表現する*ということを一つの目標にしました。

=== 準備
自分の準備としては、要所要所に数字を書いたうえでピアノでちょっと弾いてみて、歌い方を計画するといういつもの感じでした。歌い方の計画は、高音などストレスがかかる部分の「前」で頑張ることを意識して立てました。

リハーサルでは批判的な自意識をあえて抑えないことで、最終チェックとしての機能を果たそうとしましたが、これは正直失敗だったかも…と思っています（本番通りにやってあとでチェックする、というほうがチェックの精度的にもよかったかなと）。まあこれによって、本番の不測の事態（今までミスらなかったところをミスる、とか自意識が頭をもたげてくる、とか）を防ぐことができたかな、とは思うので、メリットがなくはなかった。ちょっと検証不足ですね。

直前の体のコンディショニングは、いつもの立ちゆる+軸タンブリング+胸フワ背フワに加え、大きく肘を回して肋骨を広げるワークをやりました。これ、ちょっと前から毎日の練習に取り入れているんですが、実際かなり胸郭が広がっていい感じです。息もかなり長くなった実感があります。歌う整体師の方が紹介していたので、なんとなく信頼度が高いのも個人的にはポイントです笑

video::2RiGxgM_waA[youtube]

=== 本番と成果
本番はなかなか良い心の姿勢でのぞめたのではないかと思っています。環境面では

. 正面からライトが照らされ、激しく眩しかった
. ステージと客席の間の地面がくぼんでいた（オケピみたいな）
. ピアノのふたが全開だった

といった特殊な点がありました。
1.は、「ごちゃごちゃ言わない(表現に適した)自我」を押し通すためのハードルとして、2.は、壁を使わずお客さんに直接声を届けるきっかけとして利用しました。3.に関しては、特に気にせず(張り合おうと思うとのどにダメージを与えてしまうので…)、のちの評価基準として使いました。

最後列に録音機を置いていたのですが、そこまでピアノに負けることもなく、ちゃんと表現できていました。ムジナの人にも「声量が上がった」とか嬉しいコメントをいただいたり。あと、最後まで喉がノーダメージだったのは個人的にとてもよかったことです。

ピアニストの方に、「意志がわかりやすい」という感想を持っていただけたようで、青木先生に習っている成果は多少出ているのかな、と思ったりしています。もう少し動作でなく歌で伝えられるとよいのだろうけど。

=== 課題
今回現出した課題としては

. i母音
.. 低音でiの母音の時、次につながらない「張った」歌い方をしてしまう
.. 短母音の時、短くなりすぎて言葉の中に入れていない
. a母音
.. 無条件に張ってしまい、フレーズ感がない
. リズム
.. 歌いだしの音が頼りなく、「フレーズが始まった」感がない
.. 3拍子のテンポをピアニストに伝えられていない

というものがありました。
それぞれ、エチュードをつくったり要素を含んだ曲を見つけたりして、今スプリント（6/7まで）に解消します。

やはり、得意なフレーズ・苦手なフレーズを見つけていくためにも、本番は定期的にやりたいですね。リサイタル、早く決めねば…